"""Visualization utilities for The Data Diamond."""
from src.viz.theme import (
    CREAM,
    DARK,
    DARK_BG,
    EMBER,
    GOLD,
    SAGE,
    SLATE,
    add_brand_footer,
    add_header,
    add_watermark,
    apply_theme,
    format_pct,
    save_card,
)
from src.viz.projections import (
    enrich_with_team_info,
    find_movers,
    plot_hitter_k_movers,
    plot_pitcher_card,
    plot_pitcher_k_movers,
    project_posteriors_forward,
)

__all__ = [
    "CREAM",
    "DARK",
    "DARK_BG",
    "EMBER",
    "GOLD",
    "SAGE",
    "SLATE",
    "add_brand_footer",
    "add_header",
    "add_watermark",
    "apply_theme",
    "enrich_with_team_info",
    "find_movers",
    "format_pct",
    "plot_hitter_k_movers",
    "plot_pitcher_card",
    "plot_pitcher_k_movers",
    "project_posteriors_forward",
    "save_card",
]
