"""
Matchup Ceiling Analysis - Final Synthesis Output
Run: myenv/Scripts/python.exe scripts/matchup_ceiling_analysis.py
"""
import pandas as pd
import numpy as np

lines = [
    "",
    "=" * 70,
    "MATCHUP MODEL CEILING ANALYSIS - FINAL SYNTHESIS",
    "=" * 70,
    "",
    "QUESTION: Has the current matchup model extracted most available signal?",
    "",
    "TABLE 1: Variance Budget for Pair-Level Rates (2022-2025, pairs >= 10 PA)",
    "-" * 70,
    "  Stat  | Marginals | Noise Floor | True Interaction | Signal Ceiling",
    "  ------+-----------+-------------+------------------+---------------",
    "  K%    |   24.5%   |    71.0%    |      4.5%        | 29.0% total",
    "  BB%   |   13.9%   |    83.0%    |      3.1%        | 17.0% total",
    "  HR/PA |    6.9%   |    98.1%    |      0.0%        |  6.9% total",
    "",
    "  NOTE: With 2018-2025 data (pairs >= 30 PA, n=666):",
    "    K%: marginals=46.2%, interaction_ceiling=1.3%",
    "  As PA per pair grows, the noise shrinks and marginals dominate more.",
    "",
    "TABLE 2: Platoon Split Magnitudes (2022-2025)",
    "-" * 70,
    "  Stat  | L vs L   | L vs R   | R vs L   | R vs R   | Max Spread | Var Expl",
    "  ------+----------+----------+----------+----------+------------+---------",
    "  K%    |  23.8%   |  22.1%   |  22.4%   |  23.0%   |   1.75 pp  |   0.0%",
    "  BB%   |   7.9%   |   9.6%   |   8.5%   |   7.3%   |   2.34 pp  |   1.5%",
    "  HR/PA |   2.4%   |   3.3%   |   3.2%   |   3.0%   |   0.92 pp  |   0.2%",
    "",
    "  NOTE: Platoon explains <2% of total pair variance for all stats.",
    "  Marginals already capture platoon because batter/pitcher rates",
    "  implicitly reflect their platoon-mixed rates.",
    "",
    "TABLE 3: Repeatability of Pair-Specific Effects",
    "-" * 70,
    "  Test                              | K%     | BB%",
    "  ----------------------------------+--------+--------",
    "  Raw H1/H2 correlation             | 0.272  | 0.154",
    "  Residual H1/H2 corr (post-marg)  | 0.089  | 0.038",
    "  YoY raw correlation (2022-2023)   | 0.452  | 0.142",
    "  YoY residual corr (post-marg)     | 0.090  | -0.013",
    "",
    "  INTERPRETATION: After removing marginal effects:",
    "    - K% pair residuals: weak but non-zero repeatability (r=0.09)",
    "    - BB% pair residuals: essentially zero repeatability (r=-0.01)",
    "    - This confirms pair-specific interaction is mostly noise.",
    "",
    "TABLE 4: PA Threshold and Signal-to-Noise Ratio (K%)",
    "-" * 70,
    "  Min PA | N Pairs | Obs Resid SD | Noise SD | True Signal SD | SNR  | Opt Weight",
    "  -------+---------+--------------+----------+----------------+------+-----------",
    "  10 PA  |  7,332  |   0.1173     |  0.1137  |    0.0287      | 0.063 |  6.0%",
    "  20 PA  |    637  |   0.0878     |  0.0836  |    0.0268      | 0.102 |  9.3%",
    "  30 PA  |     56  |   0.0771     |  0.0713  |    0.0293      | 0.169 | 14.5%",
    "  50 PA  |      0  |     --       |    --    |      --        |  --   |   --",
    "",
    "  NOTE: Even at 30 PA per pair, optimal shrinkage weight is only ~15%.",
    "  At 10 PA (typical), optimal weight is ~6%.",
    "  No real-life pairs exceed 69 PA in 8 seasons of data.",
    "",
    "TABLE 5: Pitch-Type Whiff Rate vs Pitcher K Rate (YoY Prediction)",
    "-" * 70,
    "  Predictor      | 2022->2023 | 2023->2024 | 2024->2025 | Avg R2",
    "  ---------------+------------+------------+------------+-------",
    "  Pitcher K rate | R2=0.237   | R2=0.175   | R2=0.149   | 0.187",
    "  Whiff rate     | R2=0.223   | R2=0.157   | R2=0.157   | 0.179",
    "  Arsenal whiff  | R2=0.231   | R2=0.164   | R2=0.164   | 0.186",
    "",
    "  Concurrent within-season:",
    "    k_rate vs whiff_rate:    r=0.720",
    "    k_rate vs arsenal_whiff: r=0.714",
    "    whiff_rate vs arsenal_whiff: r=0.987 (essentially identical!)",
    "",
    "TABLE 6: Pitch-Type Granularity Signal Above Marginals",
    "-" * 70,
    "  Model                             | R2 on pairs >= 20 PA",
    "  ----------------------------------+---------------------",
    "  Marginals (batter + pitcher - lg) | 0.313",
    "  PT-whiff adjusted pitcher K       | negative (overfit)",
    "  PT matchup score (raw mult)       | 0.190",
    "",
    "  Residual correlation (PT score vs K residual): r=0.061",
    "  (Near zero -- pitch-type matching adds no signal beyond marginals)",
    "",
    "=" * 70,
    "CONCLUSIONS",
    "=" * 70,
    "",
    "1. MARGINAL SIGNAL BUDGET:",
    "   K%: marginals explain 24.5-46.2% of pair variance (rest is noise)",
    "   BB%: marginals explain 13.9-35.8% (mostly noise at pair level)",
    "   HR/PA: marginals explain 6.9% (essentially all residual is noise)",
    "",
    "2. TRUE INTERACTION CEILING:",
    "   K%: ~4.5% of total pair variance is true interaction (not noise)",
    "   BB%: ~3.1% true interaction",
    "   HR/PA: ~0% true interaction (binomial noise exceeds total residual)",
    "",
    "3. PLATOON IS ALREADY IN MARGINALS:",
    "   Platoon spreads are small (1.75 pp K, 2.34 pp BB) and",
    "   marginals already capture platoon effects since overall rates",
    "   are platoon-mixed. Adding explicit platoon to the model gives",
    "   near-zero additional variance explained (0-1.5%).",
    "",
    "4. RESIDUAL REPEATABILITY IS NEAR ZERO:",
    "   After removing marginals, pair K% residuals repeat at r=0.09",
    "   (H1/H2 and YoY). BB% residuals are r=-0.01 (pure noise).",
    "   This means pair-specific effects CANNOT be learned reliably.",
    "",
    "5. PITCH-TYPE MATCHING ADDS NO SIGNAL:",
    "   whiff_rate vs arsenal_whiff r=0.987 -- they are interchangeable.",
    "   PT granularity does NOT outperform pitcher K rate for K prediction.",
    "   Residual corr of PT matchup score vs K residual: r=0.06 (noise).",
    "",
    "6. CURRENT MODEL IS AT CEILING:",
    "   The current matchup model correctly captures marginal effects",
    "   (batter + pitcher K rates). The remaining 4.5% of K variance",
    "   that could theoretically be interaction is nearly unrepeatable",
    "   (r=0.09 YoY) and requires 30+ PA to have SNR > 0.17.",
    "   The dampening factors (K x0.55, BB x0.40, HR x0.20) are",
    "   appropriate -- HR especially should be near zero.",
    "",
    "7. WHERE ACTUAL IMPROVEMENT COULD COME FROM:",
    "   - NOT from more pitch-type granularity (r=0.987 collinearity)",
    "   - NOT from explicit platoon (already in marginals, <2% var)",
    "   - MAYBE from higher-quality batter/pitcher talent estimates",
    "     (better priors, more stable K% estimates = better marginals)",
    "   - MAYBE from count-level models (count-specific K rates)",
    "   - Diminishing returns: any fix to Layer 2 matchup will have",
    "     <5% upside on total K variance at the pair level.",
    "",
]

for line in lines:
    print(line)
